WITH repayment_and_default AS (SELECT
      *,
      1=1 -- no filter on 'repayment_and_default.numerator_transaction_type_filter'
 AS NUMERATOR_TRANSACTION_TYPE_FILTER_FLAG
      FROM  BUSINESS_DB.BI_REPORTING.REPAYMENT_AND_DEFAULT_KE



    )
SELECT
    (TO_CHAR(DATE_TRUNC('month', (credit_loan_basic.LOCAL_FIRST_LOAN_DISBURSED_TIME::TIMESTAMP_NTZ) ), 'YYYY-MM')) AS "credit_people_basic.first_loan_local_disbursement_month",
    (TIMESTAMPDIFF(MONTH, (credit_loan_basic.LOCAL_FIRST_LOAN_DISBURSED_TIME::TIMESTAMP_NTZ)::TIMESTAMP_NTZ , (credit_loan_basic.local_disbursement_time::TIMESTAMP_NTZ) ) + CASE WHEN TIMESTAMPDIFF(SECOND, DATE_TRUNC('month', (credit_loan_basic.local_disbursement_time::TIMESTAMP_NTZ) ), (credit_loan_basic.local_disbursement_time::TIMESTAMP_NTZ) ) = TIMESTAMPDIFF(SECOND, DATE_TRUNC('month', (credit_loan_basic.LOCAL_FIRST_LOAN_DISBURSED_TIME::TIMESTAMP_NTZ)::TIMESTAMP_NTZ ), (credit_loan_basic.LOCAL_FIRST_LOAN_DISBURSED_TIME::TIMESTAMP_NTZ)::TIMESTAMP_NTZ ) THEN 0 WHEN TIMESTAMPDIFF(SECOND, DATE_TRUNC('month', (credit_loan_basic.local_disbursement_time::TIMESTAMP_NTZ) ), (credit_loan_basic.local_disbursement_time::TIMESTAMP_NTZ) ) < TIMESTAMPDIFF(SECOND, DATE_TRUNC('month', (credit_loan_basic.LOCAL_FIRST_LOAN_DISBURSED_TIME::TIMESTAMP_NTZ)::TIMESTAMP_NTZ ), (credit_loan_basic.LOCAL_FIRST_LOAN_DISBURSED_TIME::TIMESTAMP_NTZ)::TIMESTAMP_NTZ ) THEN CASE WHEN (credit_loan_basic.LOCAL_FIRST_LOAN_DISBURSED_TIME::TIMESTAMP_NTZ)::TIMESTAMP_NTZ  < (credit_loan_basic.local_disbursement_time::TIMESTAMP_NTZ)  THEN -1 ELSE 0 END ELSE CASE WHEN (credit_loan_basic.LOCAL_FIRST_LOAN_DISBURSED_TIME::TIMESTAMP_NTZ)::TIMESTAMP_NTZ  > (credit_loan_basic.local_disbursement_time::TIMESTAMP_NTZ)  THEN 1 ELSE 0 END END) AS "credit_loan_basic.months_since_first_loan_disbursed",
    COUNT(DISTINCT credit_loan_basic.PERSON_ID ) AS "credit_loan_basic.count_borrowers",
    COUNT(DISTINCT credit_loan_basic.LOAN_APPLICATION_ID ) AS "credit_loan_basic.count_loans",
    COALESCE(CAST( ( SUM(DISTINCT (CAST(FLOOR(COALESCE( credit_loan_basic.AMOUNT  ,0)*(1000000*1.0)) AS DECIMAL(38,0))) + (TO_NUMBER(MD5( credit_loan_basic.LOAN_APPLICATION_ID  ), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0) ) - SUM(DISTINCT (TO_NUMBER(MD5( credit_loan_basic.LOAN_APPLICATION_ID  ), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0)) )  AS DOUBLE PRECISION) / CAST((1000000*1.0) AS DOUBLE PRECISION), 0) AS "credit_loan_basic.total_amount",
    COALESCE(CAST( ( SUM(DISTINCT (CAST(FLOOR(COALESCE( credit_loan_basic.INTEREST_ASSESSED  ,0)*(1000000*1.0)) AS DECIMAL(38,0))) + (TO_NUMBER(MD5( credit_loan_basic.LOAN_APPLICATION_ID  ), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0) ) - SUM(DISTINCT (TO_NUMBER(MD5( credit_loan_basic.LOAN_APPLICATION_ID  ), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0)) )  AS DOUBLE PRECISION) / CAST((1000000*1.0) AS DOUBLE PRECISION), 0) AS "credit_loan_basic.total_interest_assessed",
    COALESCE(CAST( ( SUM(DISTINCT (CAST(FLOOR(COALESCE( credit_loan_basic.ROLLOVER_FEE_CHARGED  ,0)*(1000000*1.0)) AS DECIMAL(38,0))) + (TO_NUMBER(MD5( credit_loan_basic.LOAN_APPLICATION_ID  ), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0) ) - SUM(DISTINCT (TO_NUMBER(MD5( credit_loan_basic.LOAN_APPLICATION_ID  ), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0)) )  AS DOUBLE PRECISION) / CAST((1000000*1.0) AS DOUBLE PRECISION), 0) AS "credit_loan_basic.total_rollover_charged",
    COALESCE(CAST( ( SUM(DISTINCT (CAST(FLOOR(COALESCE( credit_loan_basic.ROLLOVER_FEE_REVERSED  ,0)*(1000000*1.0)) AS DECIMAL(38,0))) + (TO_NUMBER(MD5( credit_loan_basic.LOAN_APPLICATION_ID  ), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0) ) - SUM(DISTINCT (TO_NUMBER(MD5( credit_loan_basic.LOAN_APPLICATION_ID  ), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0)) )  AS DOUBLE PRECISION) / CAST((1000000*1.0) AS DOUBLE PRECISION), 0) AS "credit_loan_basic.total_rollover_reversed",
    NULLIF((COALESCE(CAST( ( SUM(DISTINCT (CAST(FLOOR(COALESCE(CASE WHEN  (repayment_and_default.TRANSACTION_BEFORE_7D AND (((CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END) = 'DEBIT')) AND ((repayment_and_default.DATE_PAST_DUE_7D       <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('Africa/Nairobi', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))))  THEN  (-repayment_and_default.AMOUNT )  ELSE NULL END
,0)*(1000000*1.0)) AS DECIMAL(38,0))) + (TO_NUMBER(MD5(CASE WHEN  (repayment_and_default.TRANSACTION_BEFORE_7D AND (((CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END) = 'DEBIT')) AND ((repayment_and_default.DATE_PAST_DUE_7D       <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('Africa/Nairobi', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))))  THEN  (repayment_and_default.ID )  ELSE NULL END
), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0) ) - SUM(DISTINCT (TO_NUMBER(MD5(CASE WHEN  (repayment_and_default.TRANSACTION_BEFORE_7D AND (((CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END) = 'DEBIT')) AND ((repayment_and_default.DATE_PAST_DUE_7D       <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('Africa/Nairobi', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))))  THEN  (repayment_and_default.ID )  ELSE NULL END
), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0)) )  AS DOUBLE PRECISION) / CAST((1000000*1.0) AS DOUBLE PRECISION), 0) - COALESCE(CAST( ( SUM(DISTINCT (CAST(FLOOR(COALESCE(CASE WHEN  (repayment_and_default.TRANSACTION_BEFORE_7D AND (((CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END) = 'CREDIT')) AND (loan_balance_details.TYPE   IN (2,3,9)) AND repayment_and_default.NUMERATOR_TRANSACTION_TYPE_FILTER_FLAG AND ((repayment_and_default.DATE_PAST_DUE_7D       <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('Africa/Nairobi', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))))  THEN  (repayment_and_default.AMOUNT )  ELSE NULL END
,0)*(1000000*1.0)) AS DECIMAL(38,0))) + (TO_NUMBER(MD5(CASE WHEN  (repayment_and_default.TRANSACTION_BEFORE_7D AND (((CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END) = 'CREDIT')) AND (loan_balance_details.TYPE   IN (2,3,9)) AND repayment_and_default.NUMERATOR_TRANSACTION_TYPE_FILTER_FLAG AND ((repayment_and_default.DATE_PAST_DUE_7D       <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('Africa/Nairobi', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))))  THEN  (repayment_and_default.ID )  ELSE NULL END
), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0) ) - SUM(DISTINCT (TO_NUMBER(MD5(CASE WHEN  (repayment_and_default.TRANSACTION_BEFORE_7D AND (((CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END) = 'CREDIT')) AND (loan_balance_details.TYPE   IN (2,3,9)) AND repayment_and_default.NUMERATOR_TRANSACTION_TYPE_FILTER_FLAG AND ((repayment_and_default.DATE_PAST_DUE_7D       <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('Africa/Nairobi', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))))  THEN  (repayment_and_default.ID )  ELSE NULL END
), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0)) )  AS DOUBLE PRECISION) / CAST((1000000*1.0) AS DOUBLE PRECISION), 0)) / NULLIF(COALESCE(CAST( ( SUM(DISTINCT (CAST(FLOOR(COALESCE(CASE WHEN  repayment_and_default.TRANSACTION_BEFORE_7D AND (((CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END) = 'DEBIT')) AND ((repayment_and_default.DATE_PAST_DUE_7D       <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('Africa/Nairobi', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD'))))  THEN  -repayment_and_default.AMOUNT   ELSE NULL END
,0)*(1000000*1.0)) AS DECIMAL(38,0))) + (TO_NUMBER(MD5(CASE WHEN  repayment_and_default.TRANSACTION_BEFORE_7D AND (((CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END) = 'DEBIT')) AND ((repayment_and_default.DATE_PAST_DUE_7D       <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('Africa/Nairobi', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD'))))  THEN  repayment_and_default.ID   ELSE NULL END
), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0) ) - SUM(DISTINCT (TO_NUMBER(MD5(CASE WHEN  repayment_and_default.TRANSACTION_BEFORE_7D AND (((CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END) = 'DEBIT')) AND ((repayment_and_default.DATE_PAST_DUE_7D       <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('Africa/Nairobi', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD'))))  THEN  repayment_and_default.ID   ELSE NULL END
), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0)) )  AS DOUBLE PRECISION) / CAST((1000000*1.0) AS DOUBLE PRECISION), 0), 0), 0) AS "repayment_and_default.default_rate_amount_7d",
    NULLIF((COALESCE(CAST( ( SUM(DISTINCT (CAST(FLOOR(COALESCE(CASE WHEN  (repayment_and_default.TRANSACTION_BEFORE_30D AND (((CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END) = 'DEBIT')) AND ((repayment_and_default.DATE_PAST_DUE_30D      <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('Africa/Nairobi', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))))  THEN  (-repayment_and_default.AMOUNT )  ELSE NULL END
,0)*(1000000*1.0)) AS DECIMAL(38,0))) + (TO_NUMBER(MD5(CASE WHEN  (repayment_and_default.TRANSACTION_BEFORE_30D AND (((CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END) = 'DEBIT')) AND ((repayment_and_default.DATE_PAST_DUE_30D      <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('Africa/Nairobi', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))))  THEN  (repayment_and_default.ID )  ELSE NULL END
), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0) ) - SUM(DISTINCT (TO_NUMBER(MD5(CASE WHEN  (repayment_and_default.TRANSACTION_BEFORE_30D AND (((CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END) = 'DEBIT')) AND ((repayment_and_default.DATE_PAST_DUE_30D      <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('Africa/Nairobi', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))))  THEN  (repayment_and_default.ID )  ELSE NULL END
), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0)) )  AS DOUBLE PRECISION) / CAST((1000000*1.0) AS DOUBLE PRECISION), 0) - COALESCE(CAST( ( SUM(DISTINCT (CAST(FLOOR(COALESCE(CASE WHEN  (repayment_and_default.TRANSACTION_BEFORE_30D AND (((CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END) = 'CREDIT')) AND (loan_balance_details.TYPE   IN (2,3,9)) AND repayment_and_default.NUMERATOR_TRANSACTION_TYPE_FILTER_FLAG AND ((repayment_and_default.DATE_PAST_DUE_30D      <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('Africa/Nairobi', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))))  THEN  (repayment_and_default.AMOUNT )  ELSE NULL END
,0)*(1000000*1.0)) AS DECIMAL(38,0))) + (TO_NUMBER(MD5(CASE WHEN  (repayment_and_default.TRANSACTION_BEFORE_30D AND (((CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END) = 'CREDIT')) AND (loan_balance_details.TYPE   IN (2,3,9)) AND repayment_and_default.NUMERATOR_TRANSACTION_TYPE_FILTER_FLAG AND ((repayment_and_default.DATE_PAST_DUE_30D      <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('Africa/Nairobi', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))))  THEN  (repayment_and_default.ID )  ELSE NULL END
), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0) ) - SUM(DISTINCT (TO_NUMBER(MD5(CASE WHEN  (repayment_and_default.TRANSACTION_BEFORE_30D AND (((CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END) = 'CREDIT')) AND (loan_balance_details.TYPE   IN (2,3,9)) AND repayment_and_default.NUMERATOR_TRANSACTION_TYPE_FILTER_FLAG AND ((repayment_and_default.DATE_PAST_DUE_30D      <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('Africa/Nairobi', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))))  THEN  (repayment_and_default.ID )  ELSE NULL END
), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0)) )  AS DOUBLE PRECISION) / CAST((1000000*1.0) AS DOUBLE PRECISION), 0)) / NULLIF(COALESCE(CAST( ( SUM(DISTINCT (CAST(FLOOR(COALESCE(CASE WHEN  repayment_and_default.TRANSACTION_BEFORE_30D AND (((CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END) = 'DEBIT')) AND ((repayment_and_default.DATE_PAST_DUE_30D      <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('Africa/Nairobi', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD'))))  THEN  -repayment_and_default.AMOUNT   ELSE NULL END
,0)*(1000000*1.0)) AS DECIMAL(38,0))) + (TO_NUMBER(MD5(CASE WHEN  repayment_and_default.TRANSACTION_BEFORE_30D AND (((CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END) = 'DEBIT')) AND ((repayment_and_default.DATE_PAST_DUE_30D      <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('Africa/Nairobi', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD'))))  THEN  repayment_and_default.ID   ELSE NULL END
), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0) ) - SUM(DISTINCT (TO_NUMBER(MD5(CASE WHEN  repayment_and_default.TRANSACTION_BEFORE_30D AND (((CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END) = 'DEBIT')) AND ((repayment_and_default.DATE_PAST_DUE_30D      <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('Africa/Nairobi', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD'))))  THEN  repayment_and_default.ID   ELSE NULL END
), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0)) )  AS DOUBLE PRECISION) / CAST((1000000*1.0) AS DOUBLE PRECISION), 0), 0), 0) AS "repayment_and_default.default_rate_amount_30d",
    NULLIF((COALESCE(CAST( ( SUM(DISTINCT (CAST(FLOOR(COALESCE(CASE WHEN  (repayment_and_default.TRANSACTION_BEFORE_51D AND (((CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END) = 'DEBIT')) AND ((repayment_and_default.DATE_PAST_DUE_51D      <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('Africa/Nairobi', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))))  THEN  (-repayment_and_default.AMOUNT )  ELSE NULL END
,0)*(1000000*1.0)) AS DECIMAL(38,0))) + (TO_NUMBER(MD5(CASE WHEN  (repayment_and_default.TRANSACTION_BEFORE_51D AND (((CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END) = 'DEBIT')) AND ((repayment_and_default.DATE_PAST_DUE_51D      <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('Africa/Nairobi', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))))  THEN  (repayment_and_default.ID )  ELSE NULL END
), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0) ) - SUM(DISTINCT (TO_NUMBER(MD5(CASE WHEN  (repayment_and_default.TRANSACTION_BEFORE_51D AND (((CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END) = 'DEBIT')) AND ((repayment_and_default.DATE_PAST_DUE_51D      <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('Africa/Nairobi', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))))  THEN  (repayment_and_default.ID )  ELSE NULL END
), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0)) )  AS DOUBLE PRECISION) / CAST((1000000*1.0) AS DOUBLE PRECISION), 0) - COALESCE(CAST( ( SUM(DISTINCT (CAST(FLOOR(COALESCE(CASE WHEN  (repayment_and_default.TRANSACTION_BEFORE_51D AND (((CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END) = 'CREDIT')) AND (loan_balance_details.TYPE   IN (2,3,9)) AND repayment_and_default.NUMERATOR_TRANSACTION_TYPE_FILTER_FLAG AND ((repayment_and_default.DATE_PAST_DUE_51D      <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('Africa/Nairobi', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))))  THEN  (repayment_and_default.AMOUNT )  ELSE NULL END
,0)*(1000000*1.0)) AS DECIMAL(38,0))) + (TO_NUMBER(MD5(CASE WHEN  (repayment_and_default.TRANSACTION_BEFORE_51D AND (((CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END) = 'CREDIT')) AND (loan_balance_details.TYPE   IN (2,3,9)) AND repayment_and_default.NUMERATOR_TRANSACTION_TYPE_FILTER_FLAG AND ((repayment_and_default.DATE_PAST_DUE_51D      <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('Africa/Nairobi', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))))  THEN  (repayment_and_default.ID )  ELSE NULL END
), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0) ) - SUM(DISTINCT (TO_NUMBER(MD5(CASE WHEN  (repayment_and_default.TRANSACTION_BEFORE_51D AND (((CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END) = 'CREDIT')) AND (loan_balance_details.TYPE   IN (2,3,9)) AND repayment_and_default.NUMERATOR_TRANSACTION_TYPE_FILTER_FLAG AND ((repayment_and_default.DATE_PAST_DUE_51D      <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('Africa/Nairobi', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))))  THEN  (repayment_and_default.ID )  ELSE NULL END
), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0)) )  AS DOUBLE PRECISION) / CAST((1000000*1.0) AS DOUBLE PRECISION), 0)) / NULLIF(COALESCE(CAST( ( SUM(DISTINCT (CAST(FLOOR(COALESCE(CASE WHEN  repayment_and_default.TRANSACTION_BEFORE_51D AND (((CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END) = 'DEBIT')) AND ((repayment_and_default.DATE_PAST_DUE_51D      <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('Africa/Nairobi', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD'))))  THEN  -repayment_and_default.AMOUNT   ELSE NULL END
,0)*(1000000*1.0)) AS DECIMAL(38,0))) + (TO_NUMBER(MD5(CASE WHEN  repayment_and_default.TRANSACTION_BEFORE_51D AND (((CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END) = 'DEBIT')) AND ((repayment_and_default.DATE_PAST_DUE_51D      <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('Africa/Nairobi', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD'))))  THEN  repayment_and_default.ID   ELSE NULL END
), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0) ) - SUM(DISTINCT (TO_NUMBER(MD5(CASE WHEN  repayment_and_default.TRANSACTION_BEFORE_51D AND (((CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END) = 'DEBIT')) AND ((repayment_and_default.DATE_PAST_DUE_51D      <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('Africa/Nairobi', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD'))))  THEN  repayment_and_default.ID   ELSE NULL END
), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0)) )  AS DOUBLE PRECISION) / CAST((1000000*1.0) AS DOUBLE PRECISION), 0), 0), 0) AS "repayment_and_default.default_rate_amount_51d",
    NULLIF((COALESCE(CAST( ( SUM(DISTINCT (CAST(FLOOR(COALESCE(CASE WHEN  (repayment_and_default.TRANSACTION_BEFORE_365D AND (((CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END) = 'DEBIT')) AND ((repayment_and_default.DATE_PAST_DUE_365D     <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('Africa/Nairobi', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))))  THEN  (-repayment_and_default.AMOUNT )  ELSE NULL END
,0)*(1000000*1.0)) AS DECIMAL(38,0))) + (TO_NUMBER(MD5(CASE WHEN  (repayment_and_default.TRANSACTION_BEFORE_365D AND (((CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END) = 'DEBIT')) AND ((repayment_and_default.DATE_PAST_DUE_365D     <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('Africa/Nairobi', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))))  THEN  (repayment_and_default.ID )  ELSE NULL END
), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0) ) - SUM(DISTINCT (TO_NUMBER(MD5(CASE WHEN  (repayment_and_default.TRANSACTION_BEFORE_365D AND (((CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END) = 'DEBIT')) AND ((repayment_and_default.DATE_PAST_DUE_365D     <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('Africa/Nairobi', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))))  THEN  (repayment_and_default.ID )  ELSE NULL END
), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0)) )  AS DOUBLE PRECISION) / CAST((1000000*1.0) AS DOUBLE PRECISION), 0) - COALESCE(CAST( ( SUM(DISTINCT (CAST(FLOOR(COALESCE(CASE WHEN  (repayment_and_default.TRANSACTION_BEFORE_365D AND (((CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END) = 'CREDIT')) AND (loan_balance_details.TYPE   IN (2,3,9)) AND repayment_and_default.NUMERATOR_TRANSACTION_TYPE_FILTER_FLAG AND ((repayment_and_default.DATE_PAST_DUE_365D     <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('Africa/Nairobi', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))))  THEN  (repayment_and_default.AMOUNT )  ELSE NULL END
,0)*(1000000*1.0)) AS DECIMAL(38,0))) + (TO_NUMBER(MD5(CASE WHEN  (repayment_and_default.TRANSACTION_BEFORE_365D AND (((CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END) = 'CREDIT')) AND (loan_balance_details.TYPE   IN (2,3,9)) AND repayment_and_default.NUMERATOR_TRANSACTION_TYPE_FILTER_FLAG AND ((repayment_and_default.DATE_PAST_DUE_365D     <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('Africa/Nairobi', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))))  THEN  (repayment_and_default.ID )  ELSE NULL END
), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0) ) - SUM(DISTINCT (TO_NUMBER(MD5(CASE WHEN  (repayment_and_default.TRANSACTION_BEFORE_365D AND (((CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END) = 'CREDIT')) AND (loan_balance_details.TYPE   IN (2,3,9)) AND repayment_and_default.NUMERATOR_TRANSACTION_TYPE_FILTER_FLAG AND ((repayment_and_default.DATE_PAST_DUE_365D     <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('Africa/Nairobi', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))))  THEN  (repayment_and_default.ID )  ELSE NULL END
), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0)) )  AS DOUBLE PRECISION) / CAST((1000000*1.0) AS DOUBLE PRECISION), 0)) / NULLIF(COALESCE(CAST( ( SUM(DISTINCT (CAST(FLOOR(COALESCE(CASE WHEN  repayment_and_default.TRANSACTION_BEFORE_365D AND (((CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END) = 'DEBIT')) AND ((repayment_and_default.DATE_PAST_DUE_365D     <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('Africa/Nairobi', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD'))))  THEN  -repayment_and_default.AMOUNT   ELSE NULL END
,0)*(1000000*1.0)) AS DECIMAL(38,0))) + (TO_NUMBER(MD5(CASE WHEN  repayment_and_default.TRANSACTION_BEFORE_365D AND (((CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END) = 'DEBIT')) AND ((repayment_and_default.DATE_PAST_DUE_365D     <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('Africa/Nairobi', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD'))))  THEN  repayment_and_default.ID   ELSE NULL END
), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0) ) - SUM(DISTINCT (TO_NUMBER(MD5(CASE WHEN  repayment_and_default.TRANSACTION_BEFORE_365D AND (((CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END) = 'DEBIT')) AND ((repayment_and_default.DATE_PAST_DUE_365D     <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('Africa/Nairobi', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD'))))  THEN  repayment_and_default.ID   ELSE NULL END
), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0)) )  AS DOUBLE PRECISION) / CAST((1000000*1.0) AS DOUBLE PRECISION), 0), 0), 0) AS "repayment_and_default.default_rate_amount_365d"
FROM  BUSINESS_DB.CREDIT.PEOPLE_BASIC_KE

   AS credit_people_basic
LEFT JOIN  BUSINESS_DB.CREDIT.APPLICATION_BASIC_KE

   AS credit_application_basic ON credit_people_basic.PERSON_ID = credit_application_basic.PERSON_ID
LEFT JOIN  BUSINESS_DB.CREDIT.LOAN_BASIC_KE

   AS credit_loan_basic ON credit_application_basic.LOAN_APPLICATION_ID = credit_loan_basic.LOAN_APPLICATION_ID
INNER JOIN  BUSINESS_DB.CREDIT.TRANSACTION_BASIC_KE
    AS loan_balance_details ON credit_loan_basic.LOAN_APPLICATION_ID = loan_balance_details.CORR_LOAN_APPLICATION_ID
INNER JOIN repayment_and_default ON loan_balance_details.ID = repayment_and_default.ID and  loan_balance_details.LOAN_APPLICATION_ID = repayment_and_default.LOAN_APPLICATION_ID
WHERE ((credit_loan_basic.LOCAL_FIRST_LOAN_DISBURSED_TIME::TIMESTAMP_NTZ) ) >= (TO_TIMESTAMP('REPLACE_DATE')) AND ((( (credit_loan_basic.LOCAL_FIRST_LOAN_DISBURSED_TIME::TIMESTAMP_NTZ)) < (DATEADD('day', -REPLACE_DAYS, DATE_TRUNC('day', CONVERT_TIMEZONE('UTC', 'America/Los_Angeles', CAST(CURRENT_TIMESTAMP() AS TIMESTAMP_NTZ)))))))
GROUP BY
    (DATE_TRUNC('month', (credit_loan_basic.LOCAL_FIRST_LOAN_DISBURSED_TIME::TIMESTAMP_NTZ) )),
    2
ORDER BY
    1,
    3 DESC
    