WITH repayment_and_default AS (SELECT
      *, 1=1 -- no filter on 'repayment_and_default.numerator_transaction_type_filter'
 AS NUMERATOR_TRANSACTION_TYPE_FILTER_FLAG
      FROM  BUSINESS_DB.BI_REPORTING.REPAYMENT_AND_DEFAULT_MX


       where date_type = 'due_date'


    )
  ,  disbursed_first_loan_credit_score_quantile AS (SELECT flq.person_id, flq.credit_score, flq.model_version, flq.score_rank, l.local_disbursement_time local_date_time
          FROM
                 BUSINESS_DB.CREDIT.FIRST_LOAN_CREDIT_SCORE_QUANTILE_MX
                  flq
          INNER JOIN

                     business_db.credit.loan_basic_mx
                      l ON flq.loan_application_id = l.loan_application_id and l.person_id = flq.person_id )
SELECT
    (TO_CHAR(DATE_TRUNC('month', (credit_loan_basic.LOCAL_FIRST_LOAN_DISBURSED_TIME::TIMESTAMP_NTZ) ), 'YYYY-MM')) AS "credit_people_basic.first_loan_local_disbursement_month",
    (TIMESTAMPDIFF(MONTH, (credit_loan_basic.LOCAL_FIRST_LOAN_DISBURSED_TIME::TIMESTAMP_NTZ)::TIMESTAMP_NTZ , (credit_loan_basic.local_disbursement_time::TIMESTAMP_NTZ) ) + CASE WHEN TIMESTAMPDIFF(SECOND, DATE_TRUNC('month', (credit_loan_basic.local_disbursement_time::TIMESTAMP_NTZ) ), (credit_loan_basic.local_disbursement_time::TIMESTAMP_NTZ) ) = TIMESTAMPDIFF(SECOND, DATE_TRUNC('month', (credit_loan_basic.LOCAL_FIRST_LOAN_DISBURSED_TIME::TIMESTAMP_NTZ)::TIMESTAMP_NTZ ), (credit_loan_basic.LOCAL_FIRST_LOAN_DISBURSED_TIME::TIMESTAMP_NTZ)::TIMESTAMP_NTZ ) THEN 0 WHEN TIMESTAMPDIFF(SECOND, DATE_TRUNC('month', (credit_loan_basic.local_disbursement_time::TIMESTAMP_NTZ) ), (credit_loan_basic.local_disbursement_time::TIMESTAMP_NTZ) ) < TIMESTAMPDIFF(SECOND, DATE_TRUNC('month', (credit_loan_basic.LOCAL_FIRST_LOAN_DISBURSED_TIME::TIMESTAMP_NTZ)::TIMESTAMP_NTZ ), (credit_loan_basic.LOCAL_FIRST_LOAN_DISBURSED_TIME::TIMESTAMP_NTZ)::TIMESTAMP_NTZ ) THEN CASE WHEN (credit_loan_basic.LOCAL_FIRST_LOAN_DISBURSED_TIME::TIMESTAMP_NTZ)::TIMESTAMP_NTZ  < (credit_loan_basic.local_disbursement_time::TIMESTAMP_NTZ)  THEN -1 ELSE 0 END ELSE CASE WHEN (credit_loan_basic.LOCAL_FIRST_LOAN_DISBURSED_TIME::TIMESTAMP_NTZ)::TIMESTAMP_NTZ  > (credit_loan_basic.local_disbursement_time::TIMESTAMP_NTZ)  THEN 1 ELSE 0 END END) AS "credit_loan_basic.months_since_first_loan_disbursed",
    (CASE
          WHEN (disbursed_first_loan_credit_score_quantile.model_version in ('gambit.mx.3.0','gambit.mx.3.0.atlas') AND  disbursed_first_loan_credit_score_quantile.credit_score BETWEEN 0 AND 0.633) OR (disbursed_first_loan_credit_score_quantile.model_version in ('gambit.mx.4.0.atlas') AND disbursed_first_loan_credit_score_quantile.credit_score BETWEEN 0 AND 0.623) THEN 1
          WHEN (disbursed_first_loan_credit_score_quantile.model_version in ('gambit.mx.3.0','gambit.mx.3.0.atlas') AND  disbursed_first_loan_credit_score_quantile.credit_score BETWEEN 0.633 AND 0.681) OR (disbursed_first_loan_credit_score_quantile.model_version in ('gambit.mx.4.0.atlas') AND disbursed_first_loan_credit_score_quantile.credit_score BETWEEN 0.623 AND 0.681) THEN 2
          WHEN (disbursed_first_loan_credit_score_quantile.model_version in ('gambit.mx.3.0','gambit.mx.3.0.atlas') AND  disbursed_first_loan_credit_score_quantile.credit_score BETWEEN 0.681 AND 0.716) OR (disbursed_first_loan_credit_score_quantile.model_version in ('gambit.mx.4.0.atlas') AND disbursed_first_loan_credit_score_quantile.credit_score BETWEEN 0.681 AND 0.722) THEN 3
          WHEN (disbursed_first_loan_credit_score_quantile.model_version in ('gambit.mx.3.0','gambit.mx.3.0.atlas') AND  disbursed_first_loan_credit_score_quantile.credit_score BETWEEN 0.716 AND 0.744) OR (disbursed_first_loan_credit_score_quantile.model_version in ('gambit.mx.4.0.atlas') AND disbursed_first_loan_credit_score_quantile.credit_score BETWEEN 0.722 AND 0.754) THEN 4
          WHEN (disbursed_first_loan_credit_score_quantile.model_version in ('gambit.mx.3.0','gambit.mx.3.0.atlas') AND  disbursed_first_loan_credit_score_quantile.credit_score BETWEEN 0.744 AND 0.77) OR (disbursed_first_loan_credit_score_quantile.model_version in ('gambit.mx.4.0.atlas') AND disbursed_first_loan_credit_score_quantile.credit_score BETWEEN 0.754 AND 0.784) THEN 5
          WHEN (disbursed_first_loan_credit_score_quantile.model_version in ('gambit.mx.3.0','gambit.mx.3.0.atlas') AND  disbursed_first_loan_credit_score_quantile.credit_score BETWEEN 0.77 AND 0.794) OR (disbursed_first_loan_credit_score_quantile.model_version in ('gambit.mx.4.0.atlas') AND disbursed_first_loan_credit_score_quantile.credit_score BETWEEN 0.784 AND 0.812) THEN 6
          WHEN (disbursed_first_loan_credit_score_quantile.model_version in ('gambit.mx.3.0','gambit.mx.3.0.atlas') AND  disbursed_first_loan_credit_score_quantile.credit_score BETWEEN 0.794 AND 0.817) OR (disbursed_first_loan_credit_score_quantile.model_version in ('gambit.mx.4.0.atlas') AND disbursed_first_loan_credit_score_quantile.credit_score BETWEEN 0.812 AND 0.839) THEN 7
          WHEN (disbursed_first_loan_credit_score_quantile.model_version in ('gambit.mx.3.0','gambit.mx.3.0.atlas') AND  disbursed_first_loan_credit_score_quantile.credit_score BETWEEN 0.817 AND 0.843) OR (disbursed_first_loan_credit_score_quantile.model_version in ('gambit.mx.4.0.atlas') AND disbursed_first_loan_credit_score_quantile.credit_score BETWEEN 0.839 AND 0.867) THEN 8
          WHEN (disbursed_first_loan_credit_score_quantile.model_version in ('gambit.mx.3.0','gambit.mx.3.0.atlas') AND  disbursed_first_loan_credit_score_quantile.credit_score BETWEEN 0.843 AND 0.875) OR (disbursed_first_loan_credit_score_quantile.model_version in ('gambit.mx.4.0.atlas') AND disbursed_first_loan_credit_score_quantile.credit_score BETWEEN 0.867 AND 0.9) THEN 9
          WHEN (disbursed_first_loan_credit_score_quantile.model_version in ('gambit.mx.3.0','gambit.mx.3.0.atlas') AND  disbursed_first_loan_credit_score_quantile.credit_score BETWEEN 0.875 AND 1) OR (disbursed_first_loan_credit_score_quantile.model_version in ('gambit.mx.4.0.atlas') AND disbursed_first_loan_credit_score_quantile.credit_score BETWEEN 0.9 AND 1) THEN 10
          END) AS "disbursed_first_loan_credit_score_quantile.mx_pltv_deciles_1",
    COUNT(DISTINCT credit_loan_basic.PERSON_ID ) AS "credit_loan_basic.count_borrowers",
    COUNT(DISTINCT credit_loan_basic.LOAN_APPLICATION_ID ) AS "credit_loan_basic.count_loans",
    COALESCE(CAST( ( SUM(DISTINCT (CAST(FLOOR(COALESCE( credit_loan_basic.AMOUNT  ,0)*(1000000*1.0)) AS DECIMAL(38,0))) + (TO_NUMBER(MD5( credit_loan_basic.LOAN_APPLICATION_ID  ), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0) ) - SUM(DISTINCT (TO_NUMBER(MD5( credit_loan_basic.LOAN_APPLICATION_ID  ), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0)) )  AS DOUBLE PRECISION) / CAST((1000000*1.0) AS DOUBLE PRECISION), 0) AS "credit_loan_basic.total_amount",
    COALESCE(CAST( ( SUM(DISTINCT (CAST(FLOOR(COALESCE( credit_loan_basic.INTEREST_ASSESSED  ,0)*(1000000*1.0)) AS DECIMAL(38,0))) + (TO_NUMBER(MD5( credit_loan_basic.LOAN_APPLICATION_ID  ), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0) ) - SUM(DISTINCT (TO_NUMBER(MD5( credit_loan_basic.LOAN_APPLICATION_ID  ), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0)) )  AS DOUBLE PRECISION) / CAST((1000000*1.0) AS DOUBLE PRECISION), 0) AS "credit_loan_basic.total_interest_assessed",
    COALESCE(CAST( ( SUM(DISTINCT (CAST(FLOOR(COALESCE( credit_loan_basic.ROLLOVER_FEE_CHARGED  ,0)*(1000000*1.0)) AS DECIMAL(38,0))) + (TO_NUMBER(MD5( credit_loan_basic.LOAN_APPLICATION_ID  ), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0) ) - SUM(DISTINCT (TO_NUMBER(MD5( credit_loan_basic.LOAN_APPLICATION_ID  ), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0)) )  AS DOUBLE PRECISION) / CAST((1000000*1.0) AS DOUBLE PRECISION), 0) AS "credit_loan_basic.total_rollover_charged",
    COALESCE(CAST( ( SUM(DISTINCT (CAST(FLOOR(COALESCE( credit_loan_basic.ROLLOVER_FEE_REVERSED  ,0)*(1000000*1.0)) AS DECIMAL(38,0))) + (TO_NUMBER(MD5( credit_loan_basic.LOAN_APPLICATION_ID  ), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0) ) - SUM(DISTINCT (TO_NUMBER(MD5( credit_loan_basic.LOAN_APPLICATION_ID  ), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0)) )  AS DOUBLE PRECISION) / CAST((1000000*1.0) AS DOUBLE PRECISION), 0) AS "credit_loan_basic.total_rollover_reversed",
    NULLIF((COALESCE(CAST( ( SUM(DISTINCT (CAST(FLOOR(COALESCE(CASE WHEN  (( repayment_and_default.TRANSACTION_BEFORE_7D   ) AND (((( CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END  )) = 'DEBIT')) AND ((  (repayment_and_default.DATE_PAST_DUE_7D       <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('America/Mexico_City', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))         )))  THEN  (-repayment_and_default.AMOUNT )  ELSE NULL END
,0)*(1000000*1.0)) AS DECIMAL(38,0))) + (TO_NUMBER(MD5(CASE WHEN  (( repayment_and_default.TRANSACTION_BEFORE_7D   ) AND (((( CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END  )) = 'DEBIT')) AND ((  (repayment_and_default.DATE_PAST_DUE_7D       <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('America/Mexico_City', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))         )))  THEN  (repayment_and_default.ID )  ELSE NULL END
), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0) ) - SUM(DISTINCT (TO_NUMBER(MD5(CASE WHEN  (( repayment_and_default.TRANSACTION_BEFORE_7D   ) AND (((( CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END  )) = 'DEBIT')) AND ((  (repayment_and_default.DATE_PAST_DUE_7D       <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('America/Mexico_City', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))         )))  THEN  (repayment_and_default.ID )  ELSE NULL END
), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0)) )  AS DOUBLE PRECISION) / CAST((1000000*1.0) AS DOUBLE PRECISION), 0) - COALESCE(CAST( ( SUM(DISTINCT (CAST(FLOOR(COALESCE(CASE WHEN  (( repayment_and_default.TRANSACTION_BEFORE_7D   ) AND (((( CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END  )) = 'CREDIT')) AND ( loan_balance_details.TYPE    IN (2,3,9)) AND ( repayment_and_default.NUMERATOR_TRANSACTION_TYPE_FILTER_FLAG  ) AND ((  (repayment_and_default.DATE_PAST_DUE_7D       <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('America/Mexico_City', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))         )))  THEN  (repayment_and_default.AMOUNT )  ELSE NULL END
,0)*(1000000*1.0)) AS DECIMAL(38,0))) + (TO_NUMBER(MD5(CASE WHEN  (( repayment_and_default.TRANSACTION_BEFORE_7D   ) AND (((( CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END  )) = 'CREDIT')) AND ( loan_balance_details.TYPE    IN (2,3,9)) AND ( repayment_and_default.NUMERATOR_TRANSACTION_TYPE_FILTER_FLAG  ) AND ((  (repayment_and_default.DATE_PAST_DUE_7D       <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('America/Mexico_City', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))         )))  THEN  (repayment_and_default.ID )  ELSE NULL END
), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0) ) - SUM(DISTINCT (TO_NUMBER(MD5(CASE WHEN  (( repayment_and_default.TRANSACTION_BEFORE_7D   ) AND (((( CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END  )) = 'CREDIT')) AND ( loan_balance_details.TYPE    IN (2,3,9)) AND ( repayment_and_default.NUMERATOR_TRANSACTION_TYPE_FILTER_FLAG  ) AND ((  (repayment_and_default.DATE_PAST_DUE_7D       <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('America/Mexico_City', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))         )))  THEN  (repayment_and_default.ID )  ELSE NULL END
), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0)) )  AS DOUBLE PRECISION) / CAST((1000000*1.0) AS DOUBLE PRECISION), 0)) / NULLIF(COALESCE(CAST( ( SUM(DISTINCT (CAST(FLOOR(COALESCE(CASE WHEN  ( repayment_and_default.TRANSACTION_BEFORE_7D   ) AND (((( CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END  )) = 'DEBIT')) AND ((  (repayment_and_default.DATE_PAST_DUE_7D       <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('America/Mexico_City', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))         ))  THEN  -repayment_and_default.AMOUNT   ELSE NULL END
,0)*(1000000*1.0)) AS DECIMAL(38,0))) + (TO_NUMBER(MD5(CASE WHEN  ( repayment_and_default.TRANSACTION_BEFORE_7D   ) AND (((( CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END  )) = 'DEBIT')) AND ((  (repayment_and_default.DATE_PAST_DUE_7D       <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('America/Mexico_City', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))         ))  THEN  repayment_and_default.ID   ELSE NULL END
), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0) ) - SUM(DISTINCT (TO_NUMBER(MD5(CASE WHEN  ( repayment_and_default.TRANSACTION_BEFORE_7D   ) AND (((( CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END  )) = 'DEBIT')) AND ((  (repayment_and_default.DATE_PAST_DUE_7D       <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('America/Mexico_City', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))         ))  THEN  repayment_and_default.ID   ELSE NULL END
), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0)) )  AS DOUBLE PRECISION) / CAST((1000000*1.0) AS DOUBLE PRECISION), 0), 0), 0) AS "repayment_and_default.default_rate_amount_7d",
    NULLIF((COALESCE(CAST( ( SUM(DISTINCT (CAST(FLOOR(COALESCE(CASE WHEN  (( repayment_and_default.TRANSACTION_BEFORE_30D   ) AND (((( CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END  )) = 'DEBIT')) AND ((  (repayment_and_default.DATE_PAST_DUE_30D      <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('America/Mexico_City', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))        )))  THEN  (-repayment_and_default.AMOUNT )  ELSE NULL END
,0)*(1000000*1.0)) AS DECIMAL(38,0))) + (TO_NUMBER(MD5(CASE WHEN  (( repayment_and_default.TRANSACTION_BEFORE_30D   ) AND (((( CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END  )) = 'DEBIT')) AND ((  (repayment_and_default.DATE_PAST_DUE_30D      <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('America/Mexico_City', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))        )))  THEN  (repayment_and_default.ID )  ELSE NULL END
), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0) ) - SUM(DISTINCT (TO_NUMBER(MD5(CASE WHEN  (( repayment_and_default.TRANSACTION_BEFORE_30D   ) AND (((( CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END  )) = 'DEBIT')) AND ((  (repayment_and_default.DATE_PAST_DUE_30D      <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('America/Mexico_City', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))        )))  THEN  (repayment_and_default.ID )  ELSE NULL END
), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0)) )  AS DOUBLE PRECISION) / CAST((1000000*1.0) AS DOUBLE PRECISION), 0) - COALESCE(CAST( ( SUM(DISTINCT (CAST(FLOOR(COALESCE(CASE WHEN  (( repayment_and_default.TRANSACTION_BEFORE_30D   ) AND (((( CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END  )) = 'CREDIT')) AND ( loan_balance_details.TYPE    IN (2,3,9)) AND ( repayment_and_default.NUMERATOR_TRANSACTION_TYPE_FILTER_FLAG  ) AND ((  (repayment_and_default.DATE_PAST_DUE_30D      <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('America/Mexico_City', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))        )))  THEN  (repayment_and_default.AMOUNT )  ELSE NULL END
,0)*(1000000*1.0)) AS DECIMAL(38,0))) + (TO_NUMBER(MD5(CASE WHEN  (( repayment_and_default.TRANSACTION_BEFORE_30D   ) AND (((( CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END  )) = 'CREDIT')) AND ( loan_balance_details.TYPE    IN (2,3,9)) AND ( repayment_and_default.NUMERATOR_TRANSACTION_TYPE_FILTER_FLAG  ) AND ((  (repayment_and_default.DATE_PAST_DUE_30D      <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('America/Mexico_City', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))        )))  THEN  (repayment_and_default.ID )  ELSE NULL END
), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0) ) - SUM(DISTINCT (TO_NUMBER(MD5(CASE WHEN  (( repayment_and_default.TRANSACTION_BEFORE_30D   ) AND (((( CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END  )) = 'CREDIT')) AND ( loan_balance_details.TYPE    IN (2,3,9)) AND ( repayment_and_default.NUMERATOR_TRANSACTION_TYPE_FILTER_FLAG  ) AND ((  (repayment_and_default.DATE_PAST_DUE_30D      <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('America/Mexico_City', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))        )))  THEN  (repayment_and_default.ID )  ELSE NULL END
), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0)) )  AS DOUBLE PRECISION) / CAST((1000000*1.0) AS DOUBLE PRECISION), 0)) / NULLIF(COALESCE(CAST( ( SUM(DISTINCT (CAST(FLOOR(COALESCE(CASE WHEN  ( repayment_and_default.TRANSACTION_BEFORE_30D   ) AND (((( CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END  )) = 'DEBIT')) AND ((  (repayment_and_default.DATE_PAST_DUE_30D      <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('America/Mexico_City', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))        ))  THEN  -repayment_and_default.AMOUNT   ELSE NULL END
,0)*(1000000*1.0)) AS DECIMAL(38,0))) + (TO_NUMBER(MD5(CASE WHEN  ( repayment_and_default.TRANSACTION_BEFORE_30D   ) AND (((( CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END  )) = 'DEBIT')) AND ((  (repayment_and_default.DATE_PAST_DUE_30D      <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('America/Mexico_City', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))        ))  THEN  repayment_and_default.ID   ELSE NULL END
), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0) ) - SUM(DISTINCT (TO_NUMBER(MD5(CASE WHEN  ( repayment_and_default.TRANSACTION_BEFORE_30D   ) AND (((( CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END  )) = 'DEBIT')) AND ((  (repayment_and_default.DATE_PAST_DUE_30D      <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('America/Mexico_City', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))        ))  THEN  repayment_and_default.ID   ELSE NULL END
), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0)) )  AS DOUBLE PRECISION) / CAST((1000000*1.0) AS DOUBLE PRECISION), 0), 0), 0) AS "repayment_and_default.default_rate_amount_30d",
    NULLIF((COALESCE(CAST( ( SUM(DISTINCT (CAST(FLOOR(COALESCE(CASE WHEN  (( repayment_and_default.TRANSACTION_BEFORE_51D   ) AND (((( CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END  )) = 'DEBIT')) AND ((  (repayment_and_default.DATE_PAST_DUE_51D      <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('America/Mexico_City', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))        )))  THEN  (-repayment_and_default.AMOUNT )  ELSE NULL END
,0)*(1000000*1.0)) AS DECIMAL(38,0))) + (TO_NUMBER(MD5(CASE WHEN  (( repayment_and_default.TRANSACTION_BEFORE_51D   ) AND (((( CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END  )) = 'DEBIT')) AND ((  (repayment_and_default.DATE_PAST_DUE_51D      <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('America/Mexico_City', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))        )))  THEN  (repayment_and_default.ID )  ELSE NULL END
), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0) ) - SUM(DISTINCT (TO_NUMBER(MD5(CASE WHEN  (( repayment_and_default.TRANSACTION_BEFORE_51D   ) AND (((( CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END  )) = 'DEBIT')) AND ((  (repayment_and_default.DATE_PAST_DUE_51D      <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('America/Mexico_City', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))        )))  THEN  (repayment_and_default.ID )  ELSE NULL END
), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0)) )  AS DOUBLE PRECISION) / CAST((1000000*1.0) AS DOUBLE PRECISION), 0) - COALESCE(CAST( ( SUM(DISTINCT (CAST(FLOOR(COALESCE(CASE WHEN  (( repayment_and_default.TRANSACTION_BEFORE_51D   ) AND (((( CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END  )) = 'CREDIT')) AND ( loan_balance_details.TYPE    IN (2,3,9)) AND ( repayment_and_default.NUMERATOR_TRANSACTION_TYPE_FILTER_FLAG  ) AND ((  (repayment_and_default.DATE_PAST_DUE_51D      <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('America/Mexico_City', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))        )))  THEN  (repayment_and_default.AMOUNT )  ELSE NULL END
,0)*(1000000*1.0)) AS DECIMAL(38,0))) + (TO_NUMBER(MD5(CASE WHEN  (( repayment_and_default.TRANSACTION_BEFORE_51D   ) AND (((( CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END  )) = 'CREDIT')) AND ( loan_balance_details.TYPE    IN (2,3,9)) AND ( repayment_and_default.NUMERATOR_TRANSACTION_TYPE_FILTER_FLAG  ) AND ((  (repayment_and_default.DATE_PAST_DUE_51D      <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('America/Mexico_City', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))        )))  THEN  (repayment_and_default.ID )  ELSE NULL END
), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0) ) - SUM(DISTINCT (TO_NUMBER(MD5(CASE WHEN  (( repayment_and_default.TRANSACTION_BEFORE_51D   ) AND (((( CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END  )) = 'CREDIT')) AND ( loan_balance_details.TYPE    IN (2,3,9)) AND ( repayment_and_default.NUMERATOR_TRANSACTION_TYPE_FILTER_FLAG  ) AND ((  (repayment_and_default.DATE_PAST_DUE_51D      <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('America/Mexico_City', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))        )))  THEN  (repayment_and_default.ID )  ELSE NULL END
), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0)) )  AS DOUBLE PRECISION) / CAST((1000000*1.0) AS DOUBLE PRECISION), 0)) / NULLIF(COALESCE(CAST( ( SUM(DISTINCT (CAST(FLOOR(COALESCE(CASE WHEN  ( repayment_and_default.TRANSACTION_BEFORE_51D   ) AND (((( CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END  )) = 'DEBIT')) AND ((  (repayment_and_default.DATE_PAST_DUE_51D      <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('America/Mexico_City', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))        ))  THEN  -repayment_and_default.AMOUNT   ELSE NULL END
,0)*(1000000*1.0)) AS DECIMAL(38,0))) + (TO_NUMBER(MD5(CASE WHEN  ( repayment_and_default.TRANSACTION_BEFORE_51D   ) AND (((( CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END  )) = 'DEBIT')) AND ((  (repayment_and_default.DATE_PAST_DUE_51D      <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('America/Mexico_City', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))        ))  THEN  repayment_and_default.ID   ELSE NULL END
), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0) ) - SUM(DISTINCT (TO_NUMBER(MD5(CASE WHEN  ( repayment_and_default.TRANSACTION_BEFORE_51D   ) AND (((( CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END  )) = 'DEBIT')) AND ((  (repayment_and_default.DATE_PAST_DUE_51D      <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('America/Mexico_City', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))        ))  THEN  repayment_and_default.ID   ELSE NULL END
), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0)) )  AS DOUBLE PRECISION) / CAST((1000000*1.0) AS DOUBLE PRECISION), 0), 0), 0) AS "repayment_and_default.default_rate_amount_51d",
    NULLIF((COALESCE(CAST( ( SUM(DISTINCT (CAST(FLOOR(COALESCE(CASE WHEN  (( repayment_and_default.TRANSACTION_BEFORE_365D   ) AND (((( CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END  )) = 'DEBIT')) AND ((  (repayment_and_default.DATE_PAST_DUE_365D     <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('America/Mexico_City', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))       )))  THEN  (-repayment_and_default.AMOUNT )  ELSE NULL END
,0)*(1000000*1.0)) AS DECIMAL(38,0))) + (TO_NUMBER(MD5(CASE WHEN  (( repayment_and_default.TRANSACTION_BEFORE_365D   ) AND (((( CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END  )) = 'DEBIT')) AND ((  (repayment_and_default.DATE_PAST_DUE_365D     <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('America/Mexico_City', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))       )))  THEN  (repayment_and_default.ID )  ELSE NULL END
), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0) ) - SUM(DISTINCT (TO_NUMBER(MD5(CASE WHEN  (( repayment_and_default.TRANSACTION_BEFORE_365D   ) AND (((( CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END  )) = 'DEBIT')) AND ((  (repayment_and_default.DATE_PAST_DUE_365D     <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('America/Mexico_City', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))       )))  THEN  (repayment_and_default.ID )  ELSE NULL END
), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0)) )  AS DOUBLE PRECISION) / CAST((1000000*1.0) AS DOUBLE PRECISION), 0) - COALESCE(CAST( ( SUM(DISTINCT (CAST(FLOOR(COALESCE(CASE WHEN  (( repayment_and_default.TRANSACTION_BEFORE_365D   ) AND (((( CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END  )) = 'CREDIT')) AND ( loan_balance_details.TYPE    IN (2,3,9)) AND ( repayment_and_default.NUMERATOR_TRANSACTION_TYPE_FILTER_FLAG  ) AND ((  (repayment_and_default.DATE_PAST_DUE_365D     <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('America/Mexico_City', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))       )))  THEN  (repayment_and_default.AMOUNT )  ELSE NULL END
,0)*(1000000*1.0)) AS DECIMAL(38,0))) + (TO_NUMBER(MD5(CASE WHEN  (( repayment_and_default.TRANSACTION_BEFORE_365D   ) AND (((( CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END  )) = 'CREDIT')) AND ( loan_balance_details.TYPE    IN (2,3,9)) AND ( repayment_and_default.NUMERATOR_TRANSACTION_TYPE_FILTER_FLAG  ) AND ((  (repayment_and_default.DATE_PAST_DUE_365D     <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('America/Mexico_City', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))       )))  THEN  (repayment_and_default.ID )  ELSE NULL END
), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0) ) - SUM(DISTINCT (TO_NUMBER(MD5(CASE WHEN  (( repayment_and_default.TRANSACTION_BEFORE_365D   ) AND (((( CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END  )) = 'CREDIT')) AND ( loan_balance_details.TYPE    IN (2,3,9)) AND ( repayment_and_default.NUMERATOR_TRANSACTION_TYPE_FILTER_FLAG  ) AND ((  (repayment_and_default.DATE_PAST_DUE_365D     <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('America/Mexico_City', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))       )))  THEN  (repayment_and_default.ID )  ELSE NULL END
), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0)) )  AS DOUBLE PRECISION) / CAST((1000000*1.0) AS DOUBLE PRECISION), 0)) / NULLIF(COALESCE(CAST( ( SUM(DISTINCT (CAST(FLOOR(COALESCE(CASE WHEN  ( repayment_and_default.TRANSACTION_BEFORE_365D   ) AND (((( CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END  )) = 'DEBIT')) AND ((  (repayment_and_default.DATE_PAST_DUE_365D     <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('America/Mexico_City', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))       ))  THEN  -repayment_and_default.AMOUNT   ELSE NULL END
,0)*(1000000*1.0)) AS DECIMAL(38,0))) + (TO_NUMBER(MD5(CASE WHEN  ( repayment_and_default.TRANSACTION_BEFORE_365D   ) AND (((( CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END  )) = 'DEBIT')) AND ((  (repayment_and_default.DATE_PAST_DUE_365D     <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('America/Mexico_City', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))       ))  THEN  repayment_and_default.ID   ELSE NULL END
), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0) ) - SUM(DISTINCT (TO_NUMBER(MD5(CASE WHEN  ( repayment_and_default.TRANSACTION_BEFORE_365D   ) AND (((( CASE WHEN (case when loan_balance_details.DESCRIPTION in ('PROCESSING_FEE','DEDUCTION','CENTRAL_GST','STATE_GST') then 0 else loan_balance_details.AMOUNT end) > 0 THEN 'CREDIT' ELSE 'DEBIT' END  )) = 'DEBIT')) AND ((  (repayment_and_default.DATE_PAST_DUE_365D     <= (TO_CHAR(TO_DATE(CONVERT_TIMEZONE('America/Mexico_City', CURRENT_TIMESTAMP()) ), 'YYYY-MM-DD')))       ))  THEN  repayment_and_default.ID   ELSE NULL END
), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') % 1.0e27)::NUMERIC(38, 0)) )  AS DOUBLE PRECISION) / CAST((1000000*1.0) AS DOUBLE PRECISION), 0), 0), 0) AS "repayment_and_default.default_rate_amount_365d"
FROM  BUSINESS_DB.CREDIT.PEOPLE_BASIC_MX

   AS credit_people_basic
LEFT JOIN  BUSINESS_DB.CREDIT.APPLICATION_BASIC_MX

   AS credit_application_basic ON credit_people_basic.PERSON_ID = credit_application_basic.PERSON_ID
LEFT JOIN  BUSINESS_DB.CREDIT.LOAN_BASIC_MX

   AS credit_loan_basic ON credit_application_basic.LOAN_APPLICATION_ID = credit_loan_basic.LOAN_APPLICATION_ID
INNER JOIN  BUSINESS_DB.CREDIT.TRANSACTION_BASIC_MX
    AS loan_balance_details ON credit_loan_basic.LOAN_APPLICATION_ID = loan_balance_details.CORR_LOAN_APPLICATION_ID
LEFT JOIN disbursed_first_loan_credit_score_quantile ON credit_people_basic.PERSON_ID = disbursed_first_loan_credit_score_quantile.PERSON_ID
INNER JOIN repayment_and_default ON loan_balance_details.ID = repayment_and_default.ID and  loan_balance_details.LOAN_APPLICATION_ID = repayment_and_default.LOAN_APPLICATION_ID
WHERE ((credit_loan_basic.LOCAL_FIRST_LOAN_DISBURSED_TIME::TIMESTAMP_NTZ) ) >= (TO_TIMESTAMP('REPLACE_DATE')) AND ((( (credit_loan_basic.LOCAL_FIRST_LOAN_DISBURSED_TIME::TIMESTAMP_NTZ)) < (DATEADD('day', -REPLACE_DAYS, DATE_TRUNC('day', CONVERT_TIMEZONE('UTC', 'America/Los_Angeles', CAST(CURRENT_TIMESTAMP() AS TIMESTAMP_NTZ))))))) AND ((CASE
          WHEN (disbursed_first_loan_credit_score_quantile.model_version in ('gambit.mx.3.0','gambit.mx.3.0.atlas') AND  disbursed_first_loan_credit_score_quantile.credit_score BETWEEN 0 AND 0.633) OR (disbursed_first_loan_credit_score_quantile.model_version in ('gambit.mx.4.0.atlas') AND disbursed_first_loan_credit_score_quantile.credit_score BETWEEN 0 AND 0.623) THEN 1
          WHEN (disbursed_first_loan_credit_score_quantile.model_version in ('gambit.mx.3.0','gambit.mx.3.0.atlas') AND  disbursed_first_loan_credit_score_quantile.credit_score BETWEEN 0.633 AND 0.681) OR (disbursed_first_loan_credit_score_quantile.model_version in ('gambit.mx.4.0.atlas') AND disbursed_first_loan_credit_score_quantile.credit_score BETWEEN 0.623 AND 0.681) THEN 2
          WHEN (disbursed_first_loan_credit_score_quantile.model_version in ('gambit.mx.3.0','gambit.mx.3.0.atlas') AND  disbursed_first_loan_credit_score_quantile.credit_score BETWEEN 0.681 AND 0.716) OR (disbursed_first_loan_credit_score_quantile.model_version in ('gambit.mx.4.0.atlas') AND disbursed_first_loan_credit_score_quantile.credit_score BETWEEN 0.681 AND 0.722) THEN 3
          WHEN (disbursed_first_loan_credit_score_quantile.model_version in ('gambit.mx.3.0','gambit.mx.3.0.atlas') AND  disbursed_first_loan_credit_score_quantile.credit_score BETWEEN 0.716 AND 0.744) OR (disbursed_first_loan_credit_score_quantile.model_version in ('gambit.mx.4.0.atlas') AND disbursed_first_loan_credit_score_quantile.credit_score BETWEEN 0.722 AND 0.754) THEN 4
          WHEN (disbursed_first_loan_credit_score_quantile.model_version in ('gambit.mx.3.0','gambit.mx.3.0.atlas') AND  disbursed_first_loan_credit_score_quantile.credit_score BETWEEN 0.744 AND 0.77) OR (disbursed_first_loan_credit_score_quantile.model_version in ('gambit.mx.4.0.atlas') AND disbursed_first_loan_credit_score_quantile.credit_score BETWEEN 0.754 AND 0.784) THEN 5
          WHEN (disbursed_first_loan_credit_score_quantile.model_version in ('gambit.mx.3.0','gambit.mx.3.0.atlas') AND  disbursed_first_loan_credit_score_quantile.credit_score BETWEEN 0.77 AND 0.794) OR (disbursed_first_loan_credit_score_quantile.model_version in ('gambit.mx.4.0.atlas') AND disbursed_first_loan_credit_score_quantile.credit_score BETWEEN 0.784 AND 0.812) THEN 6
          WHEN (disbursed_first_loan_credit_score_quantile.model_version in ('gambit.mx.3.0','gambit.mx.3.0.atlas') AND  disbursed_first_loan_credit_score_quantile.credit_score BETWEEN 0.794 AND 0.817) OR (disbursed_first_loan_credit_score_quantile.model_version in ('gambit.mx.4.0.atlas') AND disbursed_first_loan_credit_score_quantile.credit_score BETWEEN 0.812 AND 0.839) THEN 7
          WHEN (disbursed_first_loan_credit_score_quantile.model_version in ('gambit.mx.3.0','gambit.mx.3.0.atlas') AND  disbursed_first_loan_credit_score_quantile.credit_score BETWEEN 0.817 AND 0.843) OR (disbursed_first_loan_credit_score_quantile.model_version in ('gambit.mx.4.0.atlas') AND disbursed_first_loan_credit_score_quantile.credit_score BETWEEN 0.839 AND 0.867) THEN 8
          WHEN (disbursed_first_loan_credit_score_quantile.model_version in ('gambit.mx.3.0','gambit.mx.3.0.atlas') AND  disbursed_first_loan_credit_score_quantile.credit_score BETWEEN 0.843 AND 0.875) OR (disbursed_first_loan_credit_score_quantile.model_version in ('gambit.mx.4.0.atlas') AND disbursed_first_loan_credit_score_quantile.credit_score BETWEEN 0.867 AND 0.9) THEN 9
          WHEN (disbursed_first_loan_credit_score_quantile.model_version in ('gambit.mx.3.0','gambit.mx.3.0.atlas') AND  disbursed_first_loan_credit_score_quantile.credit_score BETWEEN 0.875 AND 1) OR (disbursed_first_loan_credit_score_quantile.model_version in ('gambit.mx.4.0.atlas') AND disbursed_first_loan_credit_score_quantile.credit_score BETWEEN 0.9 AND 1) THEN 10
          END)) IS NOT NULL
GROUP BY
    (DATE_TRUNC('month', (credit_loan_basic.LOCAL_FIRST_LOAN_DISBURSED_TIME::TIMESTAMP_NTZ) )),
    2,
    3
ORDER BY
    1,
    2,
    3 DESC
